### ISSUE TITLE
Date pickers don't appear in latest Chrome

### ISSUE THREAD

**Issue by woodardj** [kiro/eventmap#1]
Clicking in the "From" and "To" fields doesn't work in Chrome, throwing this error:

<img width="1440" alt="screen shot 2018-10-11 at 7 01 08 am" src="https://user-images.githubusercontent.com/557897/46805940-8c86e400-cd23-11e8-9c6a-666996893fc1.png">

**Comment by kiro** [comment]
Hi, thanks for reporting. 6 years later it's fixed!
